apiVersion: v1
kind: ConfigMap
metadata:
  name: java-app-source
  namespace: monitoring
data:
  App.java: |
    import java.sql.Connection;
    import java.sql.DriverManager;
    import java.sql.PreparedStatement;
    import java.sql.ResultSet;
    import java.sql.Statement;
    import java.time.LocalDateTime;
    import java.time.format.DateTimeFormatter;
    import java.util.Random;
    import java.util.concurrent.TimeUnit;
    
    import io.opentelemetry.api.trace.Span;

    public class App {
        public static void main(String[] args) {
            System.out.println("Starting Java Query Tester...");
            // 초기 연결 시에는 데이터베이스를 지정하지 않음
            String urlWithoutDb = "jdbc:mysql://mysql.db.svc:3306/?useSSL=false&allowPublicKeyRetrieval=true";
            String urlWithDb = "jdbc:mysql://mysql.db.svc:3306/testdb?useSSL=false&allowPublicKeyRetrieval=true";
            String user = "root";
            String password = "rootpassword123!"; // MySQL root password
            Random random = new Random();

            try {
                Class.forName("com.mysql.cj.jdbc.Driver");
                
                // 1. 초기 연결하여 데이터베이스 생성 및 테이블 생성
                try (Connection conn = DriverManager.getConnection(urlWithoutDb, user, password)) {
                    try (Statement stmt = conn.createStatement()) {
                        stmt.execute("CREATE DATABASE IF NOT EXISTS testdb"); // 데이터베이스 먼저 생성
                        stmt.execute("USE testdb"); // 생성 후 사용
                        stmt.execute("CREATE TABLE IF NOT EXISTS logs (id INT AUTO_INCREMENT PRIMARY KEY, message VARCHAR(255))");
                    }
                }

                // 2. 반복 루프: 이제 testdb에 연결하여 쿼리 실행
                while (true) {
                    try (Connection conn = DriverManager.getConnection(urlWithDb, user, password)) {
                        
                        // INSERT
                        String insertQuery = "INSERT INTO logs (message) VALUES (?)";
                        try (PreparedStatement pstmt = conn.prepareStatement(insertQuery)) {
                            pstmt.setString(1, "Log entry " + random.nextInt(1000));
                            pstmt.executeUpdate();
                        }

                        // SELECT
                        String selectQuery = "SELECT * FROM logs ORDER BY id DESC LIMIT 1";
                        try (Statement stmt = conn.createStatement();
                             ResultSet rs = stmt.executeQuery(selectQuery)) {
                            if (rs.next()) {
                                String msg = rs.getString("message");
                            }
                        }
                        
                        // Log with TraceID
                        String traceId = Span.current().getSpanContext().getTraceId();
                        String ts = LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS"));
                        System.out.printf("%s [ INFO] %d --- [main] App:Executed queries traceId: %s%n", ts, ProcessHandle.current().pid(), traceId);
                        
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    
                    TimeUnit.SECONDS.sleep(2);
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: java-query-tester
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-query-tester
  template:
    metadata:
      labels:
        app: java-query-tester
    spec:
      initContainers:
      - name: download-libs
        image: busybox
        command: ["sh", "-c"]
        args:
        - |
          wget -O /libs/opentelemetry-javaagent.jar https://github.com/open-telemetry/opentelemetry-java-instrumentation/releases/download/v1.32.1/opentelemetry-javaagent.jar
          wget -O /libs/mysql-connector-j.jar https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.2.0/mysql-connector-j-8.2.0.jar
          wget -O /libs/opentelemetry-api.jar https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-api/1.34.1/opentelemetry-api-1.34.1.jar
          wget -O /libs/opentelemetry-context.jar https://repo1.maven.org/maven2/io/opentelemetry/opentelemetry-context/1.34.1/opentelemetry-context-1.34.1.jar
        volumeMounts:
        - name: libs
          mountPath: /libs
      containers:
      - name: java-app
        image: eclipse-temurin:17-jdk
        command: ["/bin/sh", "-c"]
        args:
        - |
          javac -cp /libs/opentelemetry-api.jar:/libs/opentelemetry-context.jar /app/App.java -d /app
          
          java -javaagent:/libs/opentelemetry-javaagent.jar \
               -cp /app:/libs/mysql-connector-j.jar:/libs/opentelemetry-api.jar:/libs/opentelemetry-context.jar \
               App
        env:
        - name: OTEL_TRACES_EXPORTER
          value: "otlp"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://tempo.monitoring.svc:4318"
        - name: OTEL_SERVICE_NAME
          value: "java-query-tester"
        - name: OTEL_INSTRUMENTATION_JDBC_STATEMENT_SANITIZER_ENABLED
          value: "false"
        volumeMounts:
        - name: source
          mountPath: /app/App.java
          subPath: App.java
        - name: libs
          mountPath: /libs
        - name: app-bin
          mountPath: /app
      volumes:
      - name: source
        configMap:
          name: java-app-source
      - name: libs
        emptyDir: {}
      - name: app-bin
        emptyDir: {}