apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # 스토리지 클래스가 설정되지 않은 경우 기본 스토리지 클래스 사용 (VM 환경에 따라 다를 수 있음)
  # hostPath 등을 사용하는 PV가 필요할 수도 있으나, 일반적인 동적 프로비저닝을 가정하거나 임시로 emptyDir 사용 고려.
  # 여기서는 일반적인 PVC로 시도.
