apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: db
type: Opaque
stringData:
  # Root Password
  mysql-root-password: "rootpassword123!"
  # App User Password
  mysql-password: "demowebappuser.!"
